export const API = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    ROLES: '/auth/me/roles',
    LOGOUT: '/auth/logout',
    LOGOUT_ALL: '/auth/logout-all',
  },
  SHOPS: {
    LIST: '/shops',
    DETAIL: (id: number) => `/shops/${id}`,
    CREATE: '/shops',
    UPDATE: (id: number) => `/shops/${id}`,
    DELETE: (id: number) => `/shops/${id}`,
    MY_SHOPS: '/shops/my-shops',
    MEMBERS: (id: number) => `/shops/${id}/members`,
    MEMBER_ROLE: (shopId: number, userId: number) => `/shops/${shopId}/members/${userId}/role`,
    MEMBER_DELETE: (shopId: number, userId: number) => `/shops/${shopId}/members/${userId}`,
    PRODUCTS: (id: number) => `/shops/${id}/products`,
    PRODUCT: (shopId: number, pid: number) => `/shops/${shopId}/products/${pid}`,
    SERVICES: (id: number) => `/shops/${id}/services`,
    SERVICE: (shopId: number, sid: number) => `/shops/${shopId}/services/${sid}`,
    MECHANICS_PERFORMANCE: (id: number) => `/shops/${id}/mechanics/performance`,
    MECHANICS_PERFORMANCE_TOP: (id: number) => `/shops/${id}/mechanics/performance/top`,
    MY_PERFORMANCE: (id: number) => `/shops/${id}/mechanics/my-performance`,
  },
  MECHANIC: {
    PENDING_BOOKINGS: (shopId: number) => `/mechanic/shops/${shopId}/pending-bookings`,
    BOOKING_DETAIL: (shopId: number, apptId: number) => `/mechanic/shops/${shopId}/bookings/${apptId}`,
    BOOKING_ACTION: (shopId: number, apptId: number) => `/mechanic/shops/${shopId}/bookings/${apptId}/action`,
    TODAY_BOOKINGS: (shopId: number) => `/mechanic/shops/${shopId}/today-bookings`,
    PENDING_ORDERS: (shopId: number) => `/mechanic/shops/${shopId}/pending-orders`,
    ORDER_ACTION: (shopId: number, orderId: number) => `/mechanic/shops/${shopId}/orders/${orderId}/action`,
    ORDER_READY: (shopId: number, orderId: number) => `/mechanic/shops/${shopId}/orders/${orderId}/ready`,
    NOTIFICATIONS: '/mechanic/my-notifications',
    NOTIFICATION_READ: (id: number) => `/mechanic/notifications/${id}/read`,
  },
  QUOTATIONS: {
    SHOP_LIST: (shopId: number) => `/quotations/shops/${shopId}`,
    SHOP_DETAIL: (shopId: number, qId: number) => `/quotations/shops/${shopId}/${qId}`,
    CREATE: (shopId: number) => `/quotations/shops/${shopId}`,
    UPDATE: (shopId: number, qId: number) => `/quotations/shops/${shopId}/${qId}`,
    SEND: (shopId: number, qId: number) => `/quotations/shops/${shopId}/${qId}/send`,
  },
  INVOICES: {
    SHOP_LIST: (shopId: number) => `/invoices/shops/${shopId}`,
    SHOP_DETAIL: (shopId: number, iId: number) => `/invoices/shops/${shopId}/${iId}`,
    CREATE: (shopId: number) => `/invoices/shops/${shopId}`,
    SEND: (shopId: number, iId: number) => `/invoices/shops/${shopId}/${iId}/send`,
    PAYMENT: (shopId: number, iId: number) => `/invoices/shops/${shopId}/${iId}/payments`,
  },
  REPAIR_PROGRESS: {
    SHOP_LIST: (shopId: number) => `/repair-progress/shops/${shopId}`,
    CREATE: (shopId: number) => `/repair-progress/shops/${shopId}`,
    UPDATE: (shopId: number, pid: number) => `/repair-progress/shops/${shopId}/${pid}`,
  },
  ADMIN: {
    USERS: '/admin/users',
    USER: (id: number) => `/admin/users/${id}`,
    USER_ROLE: (id: number) => `/admin/users/${id}/role`,
    USER_STATUS: (id: number) => `/admin/users/${id}/status`,
    USER_DELETE: (id: number) => `/admin/users/${id}`,
    SHOPS: '/admin/shops',
    SHOP: (id: number) => `/admin/shops/${id}`,
    SHOP_DELETE: (id: number) => `/admin/shops/${id}`,
    APPOINTMENTS: '/admin/appointments',
    ORDERS: '/admin/orders',
    RATINGS: '/admin/ratings',
    RATING_PRODUCT_DELETE: (id: number) => `/admin/ratings/product/${id}`,
    RATING_SERVICE_DELETE: (id: number) => `/admin/ratings/service/${id}`,
    STATISTICS: '/admin/statistics',
    STATISTICS_DAILY: '/admin/statistics/daily',
  },
  CUSTOMERS: {
    SHOP_APPOINTMENTS: (shopId: number) => `/customers/shops/${shopId}/appointments`,
    APPT_STATUS: (shopId: number, apptId: number) => `/customers/shops/${shopId}/appointments/${apptId}/status`,
    SHOP_ORDERS: (shopId: number) => `/product-orders/shops/${shopId}/orders`,
    ORDER_STATUS: (shopId: number, orderId: number) => `/product-orders/shops/${shopId}/orders/${orderId}/status`,
  },
} as const;
